[project]
name = "agentcube"
version = "0.0.2"
description = "Python SDK for AgentCube Code Interpreter"
readme = "README.md"

authors = [
    { name = "Senbo Fu", email = "senbof@gmail.com" }
]

dependencies = [
    "requests",
    "PyJWT>=2.0.0",
    "cryptography"
]

[tool.setuptools]
packages = ["agentcube", "agentcube.clients", "agentcube.utils"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--strict-markers --import-mode=importlib"
testpaths = ["tests"]
