apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcap-analyzer
  namespace: default
  labels:
    app: pcap-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcap-analyzer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pcap-analyzer
    spec:
      containers:
        - name: pcap-analyzer
          image: pcap-analyzer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 1Gi
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pcap-analyzer-secrets
                  key: openai-api-key
            - name: OPENAI_API_BASE
              value: "https://api.siliconflow.cn/v1" # Change to your openAI api url
            - name: OPENAI_MODEL
              value: "Qwen/QwQ-32B"
            - name: API_URL
              value: "http://workloadmanager.agentcube.svc.cluster.local:8080"
          command: ["uv"]
          args: ["run", "pcap_analyzer.py"]
